PlasticPatrol/PlasticPatrolWeb

- package-lock.json
- package.json
- src/components/pages/PhotoPage/CategoryField/components/CategoryDropdown/components/CategoryDropdown.test.js
https://github.com/Geovation/plastic-patrol/pull/280
> add test for CategoryDropdown

- package.json
- scripts/firebase.js
- scripts/package.json
I haven't figured out via the console how to inspect individual ids so here we are
> add simple script for fetching data from firebase

- src/features/firebase/config.js
otherwise it will consider the string "false" to be true
> check if USE_PROD_DATA === 'true'

- .travis.yml
ignore the rest of the builds that are broken
> just run tests with travis

- firebase.json
- package.json
- src/App.js
- src/components/AboutPage.js
- src/components/Groups/GroupAdd.js
- src/components/Groups/GroupList.js
- src/components/Groups/GroupMain.js
- src/components/Leaderboard/Leaderboard.tsx
- src/components/ModeratorPage.tsx
- src/components/PageWrapper.tsx
- src/components/ProfilePage.tsx
- src/components/WriteFeedbackPage.js
- src/components/pages/PhotoPage/index.js
- src/components/pages/TutorialPage/components/TutorialPage/components/TutorialPage.js
- src/pages/dialogs/UploadSuccess/UploadSuccess.tsx
- src/pages/photo/components/AddNewItem/AddNewItem.tsx
- src/pages/photo/components/AddPhotoDialog/AddPhotoDialog.tsx
- src/pages/photo/components/TypeInput/TypeInput.tsx
- src/pages/photo/pages/CategorisePhotoPage/CategorisePhotoPage.stories.tsx
- src/pages/photo/pages/CategorisePhotoPage/CategorisePhotoPage.tsx
- src/pages/photo/pages/CategorisePhotoPage/utils.ts
- src/routes/Routes.tsx
- src/routes/photo/Route.tsx
- src/routes/photo/routes/categorise/links.ts
- src/routes/photo/routes/new/Route.tsx
- src/routes/upload-success/Route.tsx
- src/types/GPSLocation.ts
- src/types/Photo.ts
couple small things:
1) fixes handling for image without location
2) makes sure the user is logged in before adding a photo
3) changes some of the navigation for the add photo flow as the back buttons/close etc were conflicting with history a bit
> Litter collection bugs

- src/pages/dialogs/UploadSuccess/UploadSuccess.tsx
> 💄 change to img element so sponsor image shows up

- src/components/pages/WelcomePage/components/WelcomePage/components/WelcomePage.js
- src/components/pages/WelcomePage/components/WelcomePage/components/WelcomePage.scss
> 💄 fix tutorial height for mobile

- .firebaserc
- .github/workflows/deploy-to-dev.yml
- package.json
https://github.com/marketplace/actions/github-action-for-firebase
> 💚 add github action to deploy to dev when merged to master

- src/components/Leaderboard/Leaderboard.tsx
> 💄 fix leaderboard styles

- src/components/FeedbackReports/FeedbackReportsPage.js
> 🐛 fix feedback reports page

- cordova-app/config.xml
- cordova-app/fastlane/Fastfile
- cordova-app/package-lock.json
- package.json
- src/App.js
* remove the "still loading..." snackbar as it can hide the add photo button incorrectly
* update version
* update minSdkVersion
> Release fixes

- package.json
- src/index.js
- yarn.lock
> add sentry

- src/pages/photo/components/AddNewItem/AddNewItem.tsx
> 🐛 disable button if all fields haven't been filled in

- src/pages/photo/components/TypeInput/TypeInput.tsx
closes #130 
closes #133 
Increased the padding - means we fit less on per page but hopefully less annoying!
> 🐛 remove warning message as it's confusing users

- src/pages/about/AboutPage.tsx
> Larger About page logo

- src/components/LoginFirebase.js
> enable apple signin

- src/pages/photo/components/BarcodeScanner/BarcodeScanner.tsx
> add 'scan a barcode' text

- cypress/integration/sidedrawer.test.ts
- src/custom/config.tsx
- src/static/info.ts
for the new planet patrol branding
> update cleanup link

- cordova-app/package-lock.json
- cordova-app/package.json
- cordova-app/sentry.properties
- public/index.html
- src/index.js
so that we can capture crashes
> add sentry cordova

- scripts/admin.js
so that we can easily collect data like how many users signed up with a given email address and when
> add script for fetching users

- functions/src/barcodeLookup.ts
- scripts/admin.js
- scripts/util.js
- src/features/firebase/dbFirebase.ts
- src/pages/photo/components/BarcodeScanner/BarcodeScanner.tsx
- src/pages/photo/pages/CategorisePhotoPage/CategorisePhotoPage.tsx
add new API for looking up barcodes. This one doesn't have brand associated with it, so just use an empty string.
> add ean lookup api

- src/pages/missions/MissionsHome.tsx
Addresses first comment on https://docs.google.com/document/d/1LDiajyYeXrA5JeUfCGdkb-NyaiTfKDirJOT8DcONLpI/edit (I think)
https://user-images.githubusercontent.com/29929268/109551847-f8bb3b80-7ac8-11eb-8564-11fcab52f34a.mov
> ✨ make input clearable

- .github/workflows/merge-master.yml
release to firebase for github releases "just a getting started for opening up discussions"
> Release firebase
